Dev
RomuloOliveira/commit-messages-guide pull request #17
Opened 2019-04-21 03:53 UTC by seriouszyx

2019-04-21 04:00 UTC, seriouszyx commented
This is a first attempt of translation to Chinese. Some words which are terms from the GIT domain are not translated, such as _commit_, _rebase_.

2019-04-21 10:59 UTC, bynil commented on README_zh-CN.md
> +简单来讲，commit 就是在本地存储库中编写的本地文件的 _快照_。与一些人的想法不同的是，[git 不仅存储文件之间的差异，它还存储所有文件的完整版本](https://git-scm.com/book/eo/v1/Ekkomenci-Git-Basics#Snapshots,-Not-Differences)。对于没有从一个 commit 更改到另一个 commit 的文件，git 只存储
```suggestion
简单来讲，commit 就是在本地存储库中编写的本地文件的 _快照_。与一些人的想法不同的是，[git 不仅存储文件之间的差异，它还存储所有文件的完整版本](https://git-scm.com/book/eo/v1/Ekkomenci-Git-Basics#Snapshots,-Not-Differences)。对于两个 commit 之间没有被修改的文件，git 只存储指向前一个完全相同的文件的链接。
```

2019-04-21 11:09 UTC, bynil commented on README_zh-CN.md
> +- 在很少或没有上下文（拼写错误、格式化、确实内容）的情况下减少 commit
```suggestion
- 减少那些很少或没有上下文（拼写错误、格式化、缺失内容）的 commit
```

2019-04-22 09:25 UTC, geminiyellow reviewed
看了一下，大体感觉很不错，不过有一些翻译不太通顺或者看起来比较奇怪的地方。
明天继续看一下啊。希望大家都能有好的 commit 习惯。

2019-04-22 09:25 UTC, geminiyellow commented on README_zh-CN.md
> +它可以帮助你了解什么是 commit、为什么编写好的信息很重要、最好的实践案例以及一些技巧来计划和（重新）编写良好的 commit 历史。
```diff
- 最好的实践案例以及一些技巧来计划和（重新）编写良好的 commit 历史。
+ 以及计划和(重新)编写良好的 commit 历史的技巧和最佳实践。
```

这样看起来比较好一点

2019-04-22 09:25 UTC, geminiyellow commented on README_zh-CN.md
> +简单来讲，commit 就是在本地存储库中编写的本地文件的 _快照_。与一些人的想法不同的是，[git 不仅存储文件之间的差异，它还存储所有文件的完整版本](https://git-scm.com/book/eo/v1/Ekkomenci-Git-Basics#Snapshots,-Not-Differences)。对于没有从一个 commit 更改到另一个 commit 的文件，git 只存储
这段如果这样翻译是不是会好一点。

> 简单来讲，commit 就是在本地存储库中编写的文件的 _快照_。与印象中不同的是，[git 不仅存储不同版本文件之间的差异，还存储了所有文件的完整版本](https://git-scm.com/book/eo/v1/Ekkomenci-Git-Basics#Snapshots,-Not-Differences)。对于两个 commit 之间没有被修改的文件，git 只存储指向前一个完全相同的文件的链接。

2019-04-22 09:25 UTC, geminiyellow commented on README_zh-CN.md
> +下面的图片展示了 git 如何随着时间存储数据，其中每个“Version”都是一个 commit：
英文和中文之间空个格吧，觉得可能这样会好一丢丢，没有那么机翻感觉。

`下图显示了 git 如何随时间存储数据，其中每个 “Version” 是一个 commit：`

2019-04-22 09:25 UTC, geminiyellow commented on README_zh-CN.md
> +- 为了帮助理解一个更改
`To` 其实不翻译出来也行，比如说

```
 - 加快和简化代码审查
 - 帮助理解变更
 - 解释代码变更之外的“为什么”
 - 帮助未来的维护人员找出改进的原因和方式，使排除故障和调试变得更简单
```

2019-04-22 09:25 UTC, geminiyellow commented on README_zh-CN.md
> +这些是从我的经验、网络上的文章和其他指南中收集整理的一些实践。如果你有其他的实践（或不同意下面的某些），请随时打开 Pull Request 进行贡献。
> 这些是从我的经验、互联网文章和其他指南中整理的一些实践经验。如果你有更多的经验（或持不同意见），请随时提交 Pull Request 提供帮助。

2019-04-22 09:25 UTC, geminiyellow commented on README_zh-CN.md
> +一个 commit 信息描述了引用的更改实际**做**了什么，是它的效果，而不是被做了什么。
> commit 信息描述的是引用的变更部分实际上**做**了什么，它的效果，而不是因此被做了什么。

2019-04-22 09:25 UTC, geminiyellow commented on README_zh-CN.md
> +Use InventoryBackendPool to retrieve inventory backend
```diff
+ 用 InventoryBackendPool 获取库存
```

2019-04-22 09:25 UTC, geminiyellow commented on README_zh-CN.md
> +Used InventoryBackendPool to retrieve inventory backend
```diff
+ InventoryBackendPool 被用于获取库存
```

2019-04-22 09:25 UTC, geminiyellow commented on README_zh-CN.md
> +If applied, this commit will <commit message>
```diff
+ 如或许可，此提交将会 <提交备注>
```

2019-04-22 09:25 UTC, geminiyellow commented on README_zh-CN.md
> +If applied, this commit will use InventoryBackendPool to retrieve inventory backend
```diff
+ 如或许可，此提交将使用 InventoryBackendPool 获取库存
```

2019-04-22 09:25 UTC, geminiyellow commented on README_zh-CN.md
> +If applied, this commit will used InventoryBackendPool to retrieve inventory backend
```diff
+ 如或许可，InventoryBackendPool 将会被用于获取库存
```

2019-04-22 09:25 UTC, geminiyellow commented on README_zh-CN.md
> +这种做法可能因人而异、因团队而异、甚至因语言而异。不管是否大写，重要的是要坚持一个标准并遵守它。
**坚持**一个标准并遵守它。
可能用 **制定** 会比较好吧，坚持并遵守 应该是语法错误了。

2019-04-22 09:25 UTC, geminiyellow commented on README_zh-CN.md
> +### 尝试在不看源代码的情况下交流更改的内容
> 尽量做到只看注释便可明白而无需查看变更内容

2019-04-22 09:25 UTC, geminiyellow commented on README_zh-CN.md
> +Add `use` method to Credit model
```diff
+ 为 Credit 模块添加 `use` 方法
```

2019-04-22 09:25 UTC, geminiyellow commented on README_zh-CN.md
> +Add `use` method
```diff
+ 添加 `use` 方法
```

2019-04-22 09:25 UTC, geminiyellow commented on README_zh-CN.md
> +Increase left padding between textbox and layout frame
```diff
+ 在 textbox 和 layout frame 之间添加向左对齐
```

2019-04-22 09:25 UTC, geminiyellow commented on README_zh-CN.md
> +Adjust css
```diff
+ 就改了下 css
```

2019-04-22 10:58 UTC, jeasonstudio commented
LGTM.

2019-04-22 15:28 UTC, seriouszyx commented
> 看了一下，大体感觉很不错，不过有一些翻译不太通顺或者看起来比较奇怪的地方。
> 明天继续看一下啊。希望大家都能有好的 commit 习惯。

感谢你的校对！我已经修改了一些不太通顺的地方。在 commit 信息中，我没有直接将英文的信息翻译成中文，而是在后面的括号中备注了中文意思，因为我觉得使用英文写 commit 信息会规范一点，所以保留供大家参考。

2019-04-23 02:44 UTC, yangweijie commented
没看到 今天早上翻译了一篇 https://github.com/yangweijie/commit-messages-guide/blob/master/README_zh-CN.md

2019-04-23 03:08 UTC, geminiyellow reviewed
把剩下的一半看完了，作者那个 patch 的例子贴得太神奇了。

2019-04-23 03:08 UTC, geminiyellow commented on README_zh-CN.md
> +### 使用信息本身来解释“为什么”、“如何”和其他的细节
”原因“，”目的“，”手段“
why, what, how

2019-04-23 03:08 UTC, geminiyellow commented on README_zh-CN.md
> +Increase left padding between textbox and layout frame （在 textbox 和 layout frame 之间添加向左对齐）
个人觉得可以这样排版，所以昨天我用的是 `diff +`

```
English Version
中文版
```

这样上下排开有比较的意思，一长条的话不太利于一目十行。

2019-04-23 03:08 UTC, geminiyellow commented on README_zh-CN.md
> +像“-”、“*”和“\”的字符可以提高可读性。
> 像 `-` ，`*` 和 `\`这样的字符可提高可读性。

2019-04-23 03:08 UTC, geminiyellow commented on README_zh-CN.md
> +### 避免使用通用的信息或没有上下文的信息
你看这样可以吗，

> 避免使用无上下文的信息

**generic messages** 这个翻译成**通用信息**在中文的语感下似乎不能立刻理解是什么意思，
**无上下文**感觉就可以了。

2019-04-23 03:08 UTC, geminiyellow commented on README_zh-CN.md
> +### 限制列数
> 限制每行字数

可好？

2019-04-23 03:08 UTC, geminiyellow commented on README_zh-CN.md
> +这部分是 Atlassian 的优秀教程——["Merging vs. Rebasing"](https://www.atlassian.com/git/tutorials/merging-vs-rebasing) 的精华。
**TL;DR** 其实可以带上吧

> 优秀教程(**TL;DR**)——[

2019-04-23 03:08 UTC, geminiyellow commented on README_zh-CN.md
> +**精华：** 将你的分支一个接一个地应用于基本分支上，生成一棵新树。
？ **TL;DR** 的意思不是 `too long; dont read` 吗？直接保留就可以了吧。

2019-04-23 03:08 UTC, geminiyellow commented on README_zh-CN.md
> +**精华：** 将你的分支一个接一个地应用于基本分支上，生成一棵新树。
`一个接一个` 用 `逐个` 会不会好一点

`将分支 commit 逐个应用于基本分支，生成新树。`

2019-04-23 03:08 UTC, geminiyellow commented on README_zh-CN.md
> +**精华：** 创建一个新的 commit，称为一个 _merge commit_（合并提交），其中包含了两个分支的差异。
同样， **TL;DR:**。`称为一个` 也蛮别扭的，

`创建一个新 commit，称为 _merge commit_ ，其具有两个分支之间的差异。`

2019-04-23 03:08 UTC, geminiyellow commented on README_zh-CN.md
> +### 为什么一些人更喜欢 rebase 而不是 merge？
`而不是` 用 `而非` 会不会好一点

2019-04-23 03:08 UTC, geminiyellow commented on README_zh-CN.md
> +* 它会产生一个“干净”的历史记录，没有不必要的合并的 commit。
> 它的历史信息很 "干净"，没有无用的合并 commit

2019-04-23 03:08 UTC, geminiyellow commented on README_zh-CN.md
> +* _所见即所得_，即在代码审查中，所有的更改都来自于一个特定的、有标题的 commit，避免了在合并 commit 中隐藏的修改。
`来自` 和整句话内容上有点不匹配，是不是可以改成

> _所见即所得_，即在代码审查中，所有的更改都能在特定的、有标题的 commit 中找到，避免了隐藏在合并 commit 中的修改。

2019-04-23 03:08 UTC, geminiyellow commented on README_zh-CN.md
> +* 提交者将解决更多的合并，而且每个合并的更改都在 commit 中，并带有适当的信息。
> 通常 merge 是由提交者实行的，并会为每个转换成 commit 的 merge 书写准确的信息

2019-04-23 03:08 UTC, geminiyellow commented on README_zh-CN.md
> +    * 深入观察并审查合并的 commit 很不常见，因此避免它们可以确保所有更改都有一个属于它们的 commit。
> 通常我们不会深挖和复查 merge commit，因此尽量避免使用 merge commit，并确保个变化点都有它们所属的 commit 。

2019-04-23 03:08 UTC, geminiyellow commented on README_zh-CN.md
> +“Squashing” 是将一系列提交压缩成一个提交的过程，
commit 因为之前一直使用 commit 并没有使用到 **提交** (我倒是希望能全部变成提交)，这里也不需要转换吧。

> “Squashing” 是将一系列 commit 压缩成一个的过程，

2019-04-23 03:08 UTC, geminiyellow commented on README_zh-CN.md
> +它在很多情况下都很有用，例如：
`several situations` 是 **某些情况下** 吧

2019-04-23 03:08 UTC, geminiyellow commented on README_zh-CN.md
> +- 减少那些很少或没有上下文（拼写错误、格式化、缺失内容）的 commit
`或没有` 改成 `甚至没有` 会不会好点

2019-04-23 03:08 UTC, geminiyellow commented on README_zh-CN.md
> +- 将单独的更改连接在一起使它们更有意义
`make sense`  可能翻译成 `更通俗易懂` 会好一点。

2019-04-23 03:08 UTC, geminiyellow commented on README_zh-CN.md
> +- 重写 _还在开发_ 的 commit
`WIP` 对应 **开发中** 可能会好一点，或者保留 work in progress 也行嘛。

2019-04-23 03:08 UTC, geminiyellow commented on README_zh-CN.md
> +在多人开发的公共 commit 或共享分支上避免 rebase 和 squash。rebase 和 squash 会重写历史和现有的 commit，在共享分支的 commit（即推送到远程仓库或来自其他分支的 commit）可能会导致混乱，而且由于有分支的树和冲突人们可能会失去他们（本地和远程）的更改。
这样会不会好一点

> 避免在多人共同开发的公共 commit 或共享分支上使用 rebase 和 squash。rebase 和 squash 会改写历史记录并覆盖当前 commit，在共享分支的 commit（即推送到远程仓库或来自其他分支的 commit）上执行这些操作可能会引起混乱，由于分支产生分歧及冲突，合作者可能会因此失去他们（本地和远程）的更改。

2019-04-23 03:08 UTC, geminiyellow commented on README_zh-CN.md
> +假设我们有以下差异：
`diff` 翻译成 `分歧` 或者 `冲突` 会不会好一点

2019-04-23 03:08 UTC, geminiyellow commented on README_zh-CN.md
> +我们可以使用 `git add -p` 只添加我们想要的补丁，而不需要更改已经编写的代码。
> 我们可以使用 `git add -p` 只添加我们想要的补丁，而无需更改已有代码。

2019-04-23 03:08 UTC, geminiyellow commented on README_zh-CN.md
> +[Say thanks!](https://saythanks.io/to/RomuloOliveira)
`[点赞]` 会不会好点

2019-04-23 03:08 UTC, geminiyellow commented on README_zh-CN.md
> +感谢任何形式的帮助。一些你能帮助我的例子：
`一些你能帮助我的例子：` 这个太硬了， `譬如/例如/比如` 不是很好吗

2019-04-23 03:23 UTC, geminiyellow commented
@seriouszyx 标题可以改成 Simplified Chinese ，毕竟还有繁中。
@yangweijie 我自己也有翻，不过怎么讲，合进官方总比自己维护要好。

2019-04-24 00:01 UTC, seriouszyx commented
@geminiyellow 抱歉在火车上没有及时更改，现在已经改好了。有时间麻烦看一下有没有错误，如果可以的话就跟作者申请一下入主库。

2019-04-24 00:01 UTC, seriouszyx commented
@geminiyellow 抱歉在火车上没有及时更改，现在已经改好了。有时间麻烦看一下有没有错误，如果可以的话就跟作者申请一下入主库。

2019-04-24 02:05 UTC, geminiyellow commented
👏 LGTM，希望更多的人能看到并参与修正吧。

2019-04-25 00:39 UTC, RomuloOliveira submitted a review, later dismissed
@seriouszyx thank you so much for your contribution, I think this contribution will have a huge impact.

Thank you both @geminiyellow and @bynil for your reviews, I would never be able to do it myself.

@seriouszyx @geminiyellow Should I wait for some additional reviews before merging it?

2019-04-25 07:24 UTC, OnePieceJoker commented on README_zh-CN.md
> +
我之前也对该项目进行了中文翻译并发送了p/r，关于这段，我认为我们可以在其下接上对该模板的整体翻译。
以下是我对这段的翻译：
```
用50个字符或更少的字符总结更改

如有必要，提供更详细的说明文本。将它包装成大约72个字符。
在某些上下文中，第一行作为提交的主题，其余的文本作为主体。
分隔摘要和正文的空白行非常重要(除非完全省略正文);
如果同时运行“log”、“shortlog”和“rebase”等工具，可能会混淆。

解释此提交正在解决的问题。
关注你为什么所做的更改与(代码解释的)方式相反。
是否有副作用或其他不直观的后果更改？ 
这是解释它们的地方。

接下来的段落在空行之后。

 - 要点也可以

 - 通常使用连字符或星号作为项目符号，前面有一个空格，
   中间有空行，但约定在这里有所不同

如果您使用问题跟踪器，请将对它们的引用放在底部，如下所示:

Resolves: #123
See also: #456, #789
```

2019-04-25 08:43 UTC, seriouszyx commented on README_zh-CN.md
> +
Already fixed

2019-04-25 08:45 UTC, seriouszyx commented
LGTM  @RomuloOliveira

2019-04-25 09:38 UTC, geminiyellow reviewed
其实，翻译完了之后可以先去读一下别的东西之后再回来看看，一定有很多不妥的地方可以修正的。

2019-04-25 09:38 UTC, geminiyellow commented on README_zh-CN.md
> +这是一个模板，最初由 [Tim Pope](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) 编写，出现在 [_Pro Git Book_](https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project) 中。
`下面是参考模板`

2019-04-25 09:38 UTC, geminiyellow commented on README_zh-CN.md
> +用最多50个字符总结更改
虽然说你把之前的改了，但是这样写还是很奇怪，
用 @OnePieceJoker 的翻译会比较好一点。因为它不是最多 50 字符，而是 `in around or less`。
所以: `用 50 左右或更少的字符描述更改` 是不是好一点。

2019-04-25 09:38 UTC, geminiyellow commented on README_zh-CN.md
> +如有必要，提供更详细的说明文本。将它包装成大约72个字符。
`text` 其实可以不翻译出来，`提供更详细的说明` 就可以了吧。
` Wrap it to about 72 characters or so.` 翻译成: `包装成大约 72 个字符` 不会觉得很奇怪吗。
对应上文，这一段是不是可以写成: 

> 如有必要，可提供更详细的补充说明，并尽可能将其限定在每行 72 个字符左右。

2019-04-25 09:38 UTC, geminiyellow commented on README_zh-CN.md
> +在某些上下文中，第一行作为 commit 的主题，其余的文本作为主体。
context 确实有 上下文的意思，但是这里用 `在某些情况下` 会不会更好。

> 在某些情况下，第一行被视为 commit 的主题，文本其余部分被作为正文。

2019-04-25 09:38 UTC, geminiyellow commented on README_zh-CN.md
> +分隔摘要和正文的空白行非常重要(除非完全省略正文);
由于前面一句已经把第一行称为 **主题** ，那么这里变成 **摘要** 就变得比较奇怪了。
并且，作为承接上文结果，可以这样

> 因此，将主题从正文分割出来的空白行就显得至关重要了(除非完全省略正文)

2019-04-25 09:38 UTC, geminiyellow commented on README_zh-CN.md
> +如果同时运行“log”、“shortlog”和“rebase”等工具，可能会混淆。
可能会混淆的原因，是没有空白行，因此这句话是不是可以这样:

> 如若不然，在使用命令行，如 “log”，“shortlog” 以及 “rebase”，的时候，将会很容易混淆。

2019-04-25 09:38 UTC, geminiyellow commented on README_zh-CN.md
> +解释当前 commit 正在解决的问题。
> 解释当前 commit 所解决的问题。

2019-04-25 09:38 UTC, geminiyellow commented on README_zh-CN.md
> +关注你为什么所做的更改与(代码解释的)方式相反。
`focus` 在这里翻译成**关注**就很奇怪了。嗯……整句都错了。

> 请重点描述产生此更改的原因，而非手段（代码解释了一切）。

2019-04-25 09:38 UTC, geminiyellow commented on README_zh-CN.md
> +是否有副作用或其他不直观的后果更改？
`不直观的后果更改`，似乎简体中文没有这种说法？这句话说的就是要你描述有没有副作用。

> 是否存在副作用以及其他不直观的影响

2019-04-25 09:38 UTC, geminiyellow commented on README_zh-CN.md
> +这是解释它们的地方。
> 请在这里将其解释清楚。

2019-04-25 09:38 UTC, geminiyellow commented on README_zh-CN.md
> +接下来的段落在空行之后。
> 接下来请另起一行

2019-04-25 09:38 UTC, geminiyellow commented on README_zh-CN.md
> + - 也可以是要点。
> - 也可以使用列举要点的格式

2019-04-25 09:38 UTC, geminiyellow commented on README_zh-CN.md
> + - 通常使用连字符或星号作为项目符号，前面有一个空格，
> - 通常使用连字符(-)或星号(*)作为要点段落标记，标记与文本之间留一空格，各要点之间留一空行。但这取决于你们的约定。

2019-04-25 10:08 UTC, OnePieceJoker reviewed
关于一些链接名翻译成中文的建议

2019-04-25 10:08 UTC, OnePieceJoker commented on README_zh-CN.md
> +- [Deutsch](README_de-DE.md)
因为是中文翻译，我觉得可以把这里也翻译成中文，不知您意下如何：
- [英语](README.md)
- [葡萄牙语](README_pt-BR.md)
- [德语](README_de-DE.md)
- [西班牙语](README_es-AR.md)
- [意大利语](README_it-IT.md)

2019-04-25 10:08 UTC, OnePieceJoker commented on README_zh-CN.md
> +- [Pro Git Book - Rewriting History](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)
关于最后的文章链接，我觉得也可以翻译成英文：
- [如何编写git Commit Message](https://chris.beams.io/posts/git-commit/)
- [Pro Git Book - commit指南](https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines)
- [关于Git Commit Message的说明](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html)
- [合并与变基](https://www.atlassian.com/git/tutorials/merging-vs-rebasing)
- [Pro Git Book - 改写历史](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)

2019-04-25 10:14 UTC, OnePieceJoker commented on README_zh-CN.md
> +### 尝试在不看源代码的情况下交流更改的内容
我觉得这边的意思应该是通过查看commit message来了解变更内容
> 尽量做到通过查看 commit message 便可了解到变更内容

2019-04-25 11:11 UTC, seriouszyx commented
已经修改。

2019-04-29 00:15 UTC, seriouszyx commented
LGTM 😄

2019-04-29 06:03 UTC, gexiao requested changes

2019-04-29 06:03 UTC, gexiao commented on README_zh-CN.md
> +它可以帮助你了解什么是 commit、为什么编写好的信息很重要、最好的实践案例以及一些技巧来计划和（重新）编写良好的 commit 历史。
这个翻译好很多，「最佳实践」是个常用词。

2019-05-01 16:18 UTC, RomuloOliveira approved these changes
@seriouszyx @geminiyellow @bynil thanks again for the help. Is there additional change needed before merging it?

2019-05-02 02:50 UTC, seriouszyx commented
> @seriouszyx @geminiyellow @bynil thanks again for the help. Is there additional change needed before merging it?

No change, hope to be merged.

2019-05-02 10:01 UTC, geminiyellow commented
LGTM, please squash and merge. Thank you.

2019-05-04 14:53 UTC, RomuloOliveira commented
Thank you so much for your work on this!

2019-05-04 14:53 UTC, merged