Add Russian version
RomuloOliveira/commit-messages-guide pull request #22
Opened 2019-04-23 14:18 UTC by Dmitriy-Vas

2019-04-23 20:31 UTC, Dmitriy-Vas commented on README_ru-RU.md
> +* Больше слияний решаются автором коммита, и каждое слитое изменение находится в коммите с соответствующим сообщением
Need help with translation this line:
* More merges are resolved by the committer, and every merge change is in a commit with a proper message

2019-04-23 20:36 UTC, Dmitriy-Vas commented on README_ru-RU.md
>  ### Когда же "Squash" коммиты?
Need a good alternative to the word "Squash" in russian

2019-04-25 00:53 UTC, RomuloOliveira submitted a review, later dismissed
@Dmitriy-Vas thank you for your PR, really appreciate it!

Since I'm not able to do a thorough review (an automatic translator is far from ideal to do this job), do you know some colleagues that could help? No problem if you don't, just let me know and I'll merge it, I was lucky that people helped me and reviewed others languages. Thanks again for your contribution!

2019-04-25 11:45 UTC, Dmitriy-Vas commented
@RomuloOliveira thank you too for your work!

I'm new user in GitHub and still don't have colleagues who can help me with translations.
I just reviewed previous commit and correct some words.
This is the last revision and hope that I fixed all errors. (but I still need help with translating one line)
Please merge it when you are done with the review.

2019-04-25 11:48 UTC, lex111 reviewed
Don't rush it, don't rush it!

@Dmitriy-Vas Thank you for this :wink: 


UPD: I will continue the review later. For now, current suggestions can be accepted.

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +# Руководство по работе с коммитами
```suggestion
# Руководство по написанию коммитов
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +Руководство для понимания важности коммитов и как правильно их писать.
```suggestion
Руководство для понимания важности сообщений коммитов и того, как правильно их писать. 
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +Простыми словами, коммит это _снимок_ ваших локальных файлов, записанный в ваш локальный репозиторий.
```suggestion
Простыми словами, коммит - это _снимок_ ваших локальных файлов, записанный в локальный репозиторий.
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +Вопреки тому, что думают некоторые, [git хранит не только изменения между файлами, он хранит полную версию всех файлов](https://git-scm.com/book/eo/v1/Ekkomenci-Git-Basics#Snapshots,-Not-Differences)
```suggestion
Вопреки тому, что думают некоторые, [git хранит не только изменения между файлами, но и в целом полную версию всех файлов](https://git-scm.com/book/ru/v2/%D0%92%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5-%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B-Git).
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +- Чтобы помочь будущим разработчикам разобраться почему и как были сделаны изменения, облегчив поиск и устранение ошибок
```suggestion
- Чтобы помочь будущим разработчикам разобраться, почему и как были сделаны изменения, облегчив поиск и устранение ошибок
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +Это некоторые практики, собранные из моего опыта, статей и других руководств. Если у вас есть предложение (или вы не согласны с некоторым) не стесняйтесь открыть Pull Request и внести свой вклад.
```suggestion
Это некоторые практики, собранные из моего опыта, статей и других руководств. Если у вас есть предложение (или вы не согласны с некоторым) не стесняйтесь открыть пулреквест и внести свой вклад.
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +Сообщения коммита описывает что описанные изменения **делают**, их эффект, а не что было сделано.
```suggestion
Сообщение коммита описывает, что конкретно **делают** зафиксированные изменения, его конечный результат, а не что было сделано.
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +[Эта замечательная статья от Chris Beams](https://chris.beams.io/posts/git-commit/) даёт нам простое описание того, что может быть использовано, чтобы лучше писать сообщения коммитов в императивной ф
```suggestion
В [замечательной статье Криса Бимса (Chris Beams)](https://chris.beams.io/posts/git-commit/) ([перевод на русский](https://habr.com/ru/post/416887/)) приводится шаблон предложения, который может использоваться, чтобы лучше написать сообщения коммитов в императивной форме:
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +### Используйте заглавную первую букву
```suggestion
### Начинайте сообщение коммита с заглавной буквы
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +Причина, по которой первая буква должна быть заглавной, - в следовании грамматическому правилу об использовании заглавных букв в начале предложения.
```suggestion
Смысл этой рекомендации простой: в соответствии с правилами грамматики первое слово предложения начинается с заглавной буквы.
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +Заглавная или нет, важно придерживаться единому стандарту и следовать ему.
```suggestion
Заглавная или нет, важно придерживаться единого стандарта и следовать ему.
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +### Попытайтесь сообщить изменения без надобности смотреть исходный код
```suggestion
### Старайтесь описывать изменения так, чтобы указывать на исходный код
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +Это полезно во многих случаях (пр. несколько коммитов, различные изменения и рефакторинг), для помощи проверяющим понять о чём думал автор коммита.
```suggestion
Это полезно во многих случаях (например, когда несколько коммитов, различные изменения и рефакторинг), чтобы помочь проверяющим понять, что хотел предложить автор коммита.
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +### Используйте описание в сообщении для объяснения "почему", "для чего", "как" и дополнительные детали
```suggestion
### Используйте тело сообщения для объяснения "почему", "для чего", "как" и дополнительные детали 
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +Тема и описание сообщения разделены пустой линией.
```suggestion
Тема и описание сообщения разделены пустой строкой.
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +Дополнительные пустые линии считаются частью описания.
```suggestion
Дополнительные пустые строки считаются частью описания.
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +Такие символы как `-`, `*` и \ улучшают общую читаемость.
```suggestion
Такие символы как `-`, `*` и ` улучшают общую читаемость.
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +Для владельцев проектов: Выберите язык и пишите все сообщения коммитов используя этот язык. В идеале, он должен совпадать с комментариями в коде, стандартной локалью (для переведенных проектов), и т.
```suggestion
Для владельцев проектов: Выберите язык и пишите все сообщения коммитов на этом языке. В идеале, он должен совпадать с комментариями в коде, локалью по умолчанию (для проектов с локализацией), и т.д.
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +Для помощников: Пишите ваши сообщения коммитов используя тот же язык, что и в истории коммитов.
```suggestion
Для участников проекта: Пишите сообщения коммитов на том языке, который используется в истории коммитов.
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +Этот шаблон, [который изначально описан Tim Pope](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html), также появляется в [_Pro Git Book_](https://git-scm.com/book/en/v2/Distributed
```suggestion
Этот шаблон, [который изначально описан Тимом Поупом (Tim Pope)](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html), также упоминается в [_Pro Git Book_](https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project).
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +Эта секция является кратким пересказом превосходного руководства Atlassian, ["Merging vs. Rebasing"](https://www.atlassian.com/git/tutorials/merging-vs-rebasing).
```suggestion
Этот раздел является кратким пересказом превосходного руководства ["Merging vs. Rebasing"](https://www.atlassian.com/git/tutorials/merging-vs-rebasing) от Atlassian.
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +### Перебазировка
```suggestion
### Перебазирование
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +**Кратко:** Применяет ваше ответвление коммитов, один за другим, к базовой ветви, генерируя новое дерево.
```suggestion
**Кратко:** Применяет ваши коммиты в ветке, один за другим, к базовой ветки (например, master), генерируя новое дерево. 
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +**Кратко:** Создаёт новый коммит, называемый (соответственно) _слияющим коммитом_ (_merge commit_), с различиями между двумя ветвями.
```suggestion
**Кратко:** Создаёт новый коммит, называемый (соответственно) _коммит слияния_ (_merge commit_), с различиями между двумя ветками.
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +Я, в частности, предпочитаю перебазирование вместо слияния. Причины включают в себя:
```suggestion
Я, например, предпочитаю перебазирование вместо слияния по следующим причинам:
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +* Это генерирует "чистую" историю, без ненужных слияющих коммитов
```suggestion
* Это создает "чистую" историю, без ненужных коммитов-слияний
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +* _Что видишь - то и получаешь_, т.е. при обзоре кода все изменения идут от определенного коммита, избегая скрытые изменения в слияющих коммитах
```suggestion
* _Что видишь, то и имеешь,_, т.е. при ревью кода все изменения идут от определенного коммита, без скрытых изменений в коммитах при слиянии
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +* Больше слияний решаются автором коммита, и каждое слитое изменение находится в коммите с соответствующим сообщением
```suggestion
* Больше слияний решаются автором коммита, поэтому каждое слитое изменение находится в коммите с соответствующим сообщением
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +    * Это необычно - просматривать слияющие коммиты, поэтому избегая их, вы гарантируете что все изменения имеют коммит, к которому они относятся
```suggestion
    * Обычно не смотрят коммиты-слияния, так что таким образом все изменения зафиксированы в коммите, к которому они непосредственно относятся 
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +### Когда же "Squash" коммиты?
```suggestion
### Когда нужно делать слияние коммитов?
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +"Squashing" это процесс объединения серии коммитов в один коммит.
```suggestion
Слияние (Squashing) — это процесс объединения множества коммитов в один-единственный коммит. 
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +It's useful in several situations, e.g.:
```suggestion
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +Это полезно в нескольких ситуациях, пример:
```suggestion
Это может пригодиться в ряде ситуациях, например:
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +- Уменьшение количества коммитов с небольшим контекстом или без контекста (исправление ошибок, форматирование, забытые вещи)
```suggestion
- Уменьшение количества коммитов с небольшим контекстом или без контекста (исправление опечаток, форматирование, дополнения)
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +- Объединение отдельных изменений, которые имеют больше смысла, когда применяются вместе
```suggestion
- Объединение независимых изменений, которые лучше всего применять вместе
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +- Переписывание _WIP_ (работа в прогрессе) коммитов
```suggestion
- Переписывание коммитов в стадии _WIP_ (черновика)
```

2019-04-25 11:48 UTC, lex111 commented on README_ru-RU.md
> +### When to avoid rebase or squash?
```suggestion
```

2019-04-25 11:55 UTC, Dmitriy-Vas commented on README_ru-RU.md
> +# Руководство по работе с коммитами
This guide explains not only "writing" commits, so i think "working" will be better.

2019-04-25 11:58 UTC, lex111 commented on README_ru-RU.md
> +# Руководство по работе с коммитами
Если по _работе_, то предполагается команды или инструкции, но здесь по **большей части** именно написание.

2019-04-25 12:40 UTC, Dmitriy-Vas commented on README_ru-RU.md
> +Это полезно в нескольких ситуациях, пример:
Error:
```
Это может пригодиться в ряде ситуациях, например:
```
Fix:
```
Это может пригодиться в ряде ситуаций, например:
```

2019-04-25 12:41 UTC, lex111 commented on README_ru-RU.md
> +Это полезно в нескольких ситуациях, пример:
Исправил

2019-04-25 21:04 UTC, lex111 requested changes
@RomuloOliveira I did a review with the suggestions, after accepted them, this PR can be merged!

@Dmitriy-Vas вы можете применить мои предложения одним коммитом, посмотрите эту статью https://help.github.com/en/articles/incorporating-feedback-in-your-pull-request#applying-a-suggested-change

2019-04-25 21:04 UTC, lex111 commented on README_ru-RU.md
> +Это полезно во многих случаях (пр. несколько коммитов, различные изменения и рефакторинг), чтобы помочь проверяющим понять о чём думал автор коммита.
```suggestion
Это полезно во многих случаях (пр. несколько коммитов, различные изменения и рефакторинг), чтобы помочь проверяющим понять о чём думал автор коммита.
```

2019-04-25 21:04 UTC, lex111 commented on README_ru-RU.md
> +[Эта замечательная статья от Chris Beams](https://chris.beams.io/posts/git-commit/) даёт нам простое описание того, что может быть использовано, чтобы лучше писать сообщения коммитов в повелительном
```suggestion
В [замечательной статье Криса Бимса (Chris Beams)](https://chris.beams.io/posts/git-commit/) ([перевод на русский](https://habr.com/ru/post/416887/)) приводится шаблон предложения, который может использоваться, чтобы лучше писать сообщения коммитов в императивной форме:
```

2019-04-25 21:04 UTC, lex111 commented on README_ru-RU.md
> +### Когда же "сжимать" коммиты?
```suggestion
### Когда нужно делать слияние коммитов?
```

2019-04-25 21:04 UTC, lex111 commented on README_ru-RU.md
> +Сжатие - это процесс объединения серии коммитов в один коммит.
```suggestion
Слияние (Squashing) — это процесс объединения множества коммитов в один-единственный коммит.
```

2019-04-25 21:04 UTC, lex111 commented on README_ru-RU.md
> +Избегайте этого в публичных коммитах или в общих ветвях, где работают несколько человек.
```suggestion
Избегайте этого в публичных коммитах или в общих ветках, в которых работают несколько человек.
```

2019-04-25 21:04 UTC, lex111 commented on README_ru-RU.md
> +Это также перезаписывает историю коммитов и существующие коммиты, делая это с коммитами которые находятся в разных ветвях (пр., коммиты отправленные в удаленный репозиторий или которые идут из других
```suggestion
Перебазирование и слияние также перезаписывает историю коммитов и существующие коммиты, делая это с коммитами, которые находятся в разных ветвках (например, коммиты, отправленные в удаленный репозиторий или коммиты из других веток) могут вызвать путаницу и поэтому можно потерять изменения (как локальные, так и удаленные) из-за различающегося дерева и конфликтов.
```

2019-04-25 21:04 UTC, lex111 commented on README_ru-RU.md
> +Используйте их чтобы сжать коммиты, изменить сообщения, переписать/удалить/реорганизовать коммиты, и т.д.
```suggestion
Используйте их, чтобы объединить коммиты, изменить сообщения, переписать/удалить/изменить порядок коммитов и т.д.
```

2019-04-25 21:04 UTC, lex111 commented on README_ru-RU.md
> +Используйте для очистки коммитов без необходимости в перебазировке.
```suggestion
Используйте эту команду, чтобы привести в порядок коммиты, не прибегая к перебазированию. 
```

2019-04-25 21:04 UTC, lex111 commented on README_ru-RU.md
> +[Данная статья](http://fle.github.io/git-tip-keep-your-branch-clean-with-fixup-and-autosquash.html) имеет хорошие примеры того, как и когда это делать.
```suggestion
В [этой статье](http://fle.github.io/git-tip-keep-your-branch-clean-with-fixup-and-autosquash.html) есть хорошие примеры того, как и когда это делать.

```

2019-04-25 21:04 UTC, lex111 commented on README_ru-RU.md
> +Это очень полезно для применения коммитов, которые вы сделали в неправильной ветви, без необходимости писать их заново.
```suggestion
Эта команда может быть очень полезной для применения коммита, который был сделан в неверной ветке, чтобы не писать код заново.
```

2019-04-25 21:04 UTC, lex111 commented on README_ru-RU.md
> +Давайте представим что мы имеем следующий список различий:
```suggestion
Давайте представим, что у нас есть следующий список различий:
```

2019-04-25 21:04 UTC, lex111 commented on README_ru-RU.md
> + ## Contributing
```suggestion
 ## Участие в проекте
```

2019-04-25 21:04 UTC, lex111 commented on README_ru-RU.md
> +Мы можем использовать `git add -p` чтобы добавить только те патчи, которые нам нужны, без нужды изменять уже написанный код.
```suggestion
Мы можем выполнить `git add -p` чтобы добавить только те патчи, которые нам нужны, без необходимости изменять уже существующий код.
```

2019-04-25 21:04 UTC, lex111 commented on README_ru-RU.md
> +#### hunk 1
```suggestion
#### часть 1
```

2019-04-25 21:04 UTC, lex111 commented on README_ru-RU.md
> +#### hunk 2
```suggestion
#### часть 2
```

2019-04-25 21:04 UTC, lex111 commented on README_ru-RU.md
> +#### hunk 3
```suggestion
#### часть 3
```

2019-04-25 21:04 UTC, lex111 commented on README_ru-RU.md
> +## Нравится руководство?
```suggestion
## Нравится это руководство?
```

2019-04-25 21:04 UTC, lex111 commented on README_ru-RU.md
> +## Другие интересные вещи
```suggestion
## Кое-что интересное
```

2019-04-25 21:04 UTC, lex111 commented on README_ru-RU.md
> +Любой вид помощи будет оценен. Пример тем, с которыми вы можете помочь:
```suggestion
Любая помощь приветствуется. Вот, например, что вы можете сделать:
```

2019-04-25 21:04 UTC, lex111 commented on README_ru-RU.md
> +- Ошибки в грамматике и правописании
```suggestion
- Исправить ошибки в грамматике и правописании 
```

2019-04-25 21:04 UTC, lex111 commented on README_ru-RU.md
> +- Неверная или неполная информация
```suggestion
- Изменить неверную или неполную информацию
```

2019-04-25 23:36 UTC, Dmitriy-Vas commented
> 
> 
> @RomuloOliveira I did a review with the suggestions, after accepted them, this PR can be merged!
> 
> @Dmitriy-Vas вы можете применить мои предложения одним коммитом, посмотрите эту статью https://help.github.com/en/articles/incorporating-feedback-in-your-pull-request#applying-a-suggested-change

Mhm, didn't know this works from "files" tab, added 1 excess commit.

2019-04-26 06:05 UTC, lex111 requested changes
Final corrections

2019-04-26 06:05 UTC, lex111 commented on README_ru-RU.md
> +Слияние (Squashing) — это процесс объединения множества коммитов в один-единственный коммит.
```suggestion
Объединение (Squashing) — это процесс объединения множества коммитов в один-единственный коммит.
```

2019-04-26 06:05 UTC, lex111 commented on README_ru-RU.md
> +### Когда нужно делать слияние коммитов?
```suggestion
### Когда нужно делать объединение коммитов?
```

2019-04-26 18:43 UTC, lex111 approved these changes
LGTM :+1:

2019-04-28 21:24 UTC, RomuloOliveira approved these changes
Thank you very much @Dmitriy-Vas and @lex111

2019-04-28 21:24 UTC, merged